### ISSUE TITLE
[提案]:スプレッド構文

### ISSUE THREAD

**Issue by taiseiue** [WSOFT-Project/Losetta#100]
# スプレッド構文

## 概要

配列式中で、要素を定義するように他の配列の中身を展開できるようにしたい。

```cs
var numbers = [5,6,7,8];

var ary = [1, 2, 3, 4, …numbers, 9];
// [1,2,3,4,5,6,7,8,9]
```
## 動機

従来AliceScriptで、ある配列と配列を結合するには、次のように行う必要があった。

```cs
var numbers = [5,6,7,8];

var ary = [1, 2, 3, 4];
ary.AddRange(numbers);
ary.Add(9);
```

スプレッド構文の導入にとって、これを概要に示したように簡単に定義できる。
## 詳細設計

配列式中でのみ、`…`から始まる変数名が指定されたときに、配列の中身を展開する操作を実行する。

該当ドキュメント

- [Array - WSOFTDocs](https://docs.wsoft.ws/products/alice/api/array/)
- [式 - WSOFTDocs](https://docs.wsoft.ws/products/alice/general/expression/)

他の場所でスプレッド構文が使用されたとしても、特別な処理は行わず普通にエラーにする。
## 欠点

- 先頭にピリオドを使用する変数を定義していた場合に破壊的変更になる？
AliceScriptは先頭にピリオドを使用する識別子を許可しないため破壊的変更にはならない。

## 未確定の設計
スプレッド構文のスプレッド演算子は`…`(3点リーダー)にする？それとも`..`(2点リーダー)にする？

**Comment by taiseiue** [comment]
一旦Alice3.0に導入する計画で

**Comment by taiseiue** [comment]
@matsu-zen 
スプレッド演算子`..`(2点リーダー)か`...`(3点リーダー)どっちがいい？

```cs
// 2点リーダーver
var ary2 = [ 0,..ary1,5];

// 3点リーダー
var ary3 = [0, ...ary1 , 5];
```

**Comment by matsu-zen** [comment]
3点リーダーのほうがいいと思う。because 「…」が記号として存在するからポピュラーなんじゃね説。

**Comment by taiseiue** [comment]
これ2点とか3点リーダーやと思ってユーザーが`\u2026`とか`\u2025`とか入力したときどうする？普通にエラーにするか

**Comment by matsu-zen** [comment]
めっちゃ今気づいたけどとりあえずコミットしとくわ
