### ISSUE TITLE
[BUG]:文を式の一部に使うことを許してしまっている

### ISSUE THREAD

**Issue by taiseiue** [WSOFT-Project/Losetta#133]
**不具合の説明**
そもそも、AliceScriptには**文**と**式**の2種類の構文がある。
式の定義は`式を値があるものすべてと定義します`。となっているため、`void`型を返す=値のないものは文になる。

```cs
2 + 3;　//式
var a = 3; //文
```

これをしっかり分けることで、次のようなミスを防げる。

```cs
var a = 2;

if(a = 2) // a==2のつもりがa=2になっている
{
   print($"a = {a}");
}

// `print`は実行されなかった
```

**再現手順**
次のコードは正常に実行できてしまう。

```cs
var v = (var a = 2);
```

不具合に遭遇するための最低限の手順を示していただけるとありがたいです。

**期待する動作**
文を式の一部に使った時にエラーを発生させる。
たとえば、``文`を式中に含めることはできません`みたいな感じ。

**エラーコード**
このバグがエラーを引き起こした場合、可能であればエラーコードを記載してください。

**補足**

**Comment by matsu-zen** [comment]
流石にこれで困ってる人がいるかどうかが怪しいので修正の緊急性は低いと思われます。メジャーアップデートに回してその他修正との整合性を保った状態で出しましょう。
